### ISSUE TITLE
Loosen fastapi dependency requirements

### ISSUE THREAD

**Issue by zetoichi** [mrtolkien/fastapi_simple_security#11]
`pip install -r requirements.txt` fails to resolve dependencies, because fastapi_simple_security is trying to force an older version of fastapi. 

I Momentarily solved it by manually installing an older fastapi version in my application, but I see no reason why this should be the way to go (new versions don't introduce breaking changes).

Thanks!

**Comment by mrtolkien** [comment]
Your issue is not related to this package:
https://github.com/mrtolkien/fastapi_simple_security/blob/d124b487d522147ec6e4ba0d9f0a699781e83542/pyproject.toml#L13

**Comment by plocher** [comment]
when using pip (and not poetry...) the error is

#8 16.40 The conflict is caused by:
#8 16.40     The user requested fastapi==0.75.2
#8 16.40     fastapi-simple-security 1.0.1 depends on fastapi<0.71 and >=0.70

From the package on pypi

fastapi_simple_security-1.0.1.dist-info/METADATA:Requires-Dist: fastapi (>=0.70,<0.71)
The only other ref to fastapi in your repo is
 
[[package]]
name = "fastapi"
version = "0.70.0"
description = "FastAPI framework, high performance, easy to learn, fast to code, ready for production"
category = "main"
optional = false
python-versions = ">=3.6.1"

**Comment by mrtolkien** [comment]
I was pretty sure `^0.70` meant any version superior to 0.70 in poetry, but I pushed a new version with `>=0.70` instead.
